version: "3.8"
services:
  nginx:
    build: nginx/dev
    container_name: nginx.boringart
    restart: always
    ports:
      - 80:80

  api:
    build:
      context: api
      dockerfile: Dockerfile-dev
    container_name: api.boringart
    restart: always
    volumes:
      - "./api:/api"
    environment:
      - S3_ENDPOINT_URL=http://minio.localtest.me
      - S3_AWS_ACCESS_KEY_ID=minio_access_key
      - S3_AWS_SECRET_ACCESS_KEY=minio_secret_key

      - MONGO_URI=mongodb://mongo:27017

      - KEYCLOAK_SERVER_URL=http://keycloak.localtest.me/auth
      - KEYCLOAK_CLIENT_SECRET=6eaf3024-0302-4bd3-b542-9b7322984437

      - API_SCHEME=http
      - API_HOST=api.localtest.me
      - API_PORT=80

      - SITE_INDEX=http://boringart.localtest.me
    links:
      - "nginx:keycloak.localtest.me"
      - "nginx:minio.localtest.me"

  spa:
    build:
      context: spa
      dockerfile: Dockerfile-dev
    container_name: spa.boringart
    volumes:
      - "./spa:/spa"
    environment:
      - API_ENDPOINT=http://api.localtest.me
      - KEYCLOAK_URL=http://keycloak.localtest.me/auth
    links:
      - "nginx:keycloak.localtest.me"
      - "nginx:api.localtest.me"

  minio:
    image: minio/minio
    container_name: minio.boringart
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: minio server /data

  mongo:
    image: mongo
    container_name: mongo.boringart
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express.boringart
    restart: always
    ports:
      - 8081:8081

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog.boringart
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  keycloack:
    build: keycloak/dev
    container_name: keycloak.boringart
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
