version: "3.7"
services:
  minio:
    image: minio/minio
    volumes:
      - data:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: minio server /data
    ports:
    - 9000:9000

volumes:
  data:
