version: "3.8"
services:
  nginx:
    build: nginx/dev
    container_name: nginx.boringart
    restart: always
    ports:
      - 80:80

  webapp:
    build:
      context: webapp
      dockerfile: docker/Dockerfile-dev
    container_name: webapp.boringart
    restart: always
    volumes:
      - "./webapp:/webapp"
    environment:
      - S3_ENDPOINT_URL=http://minio.localtest.me
      - S3_AWS_ACCESS_KEY_ID=minio_access_key
      - S3_AWS_SECRET_ACCESS_KEY=minio_secret_key
      - S3_BUCKET=youtube-clone

      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DATABASE=youtube_clone

      - REDIS_URI=redis://redis:6379/1

      - SITE_SCHEME=http
      - SITE_HOST=youtube-clone.localtest.me
      - SITE_PORT=80

      - KEYCLOAK_SERVER_URL=http://keycloak.localtest.me
      - KEYCLOAK_REALM_NAME=youtube_clone
      - KEYCLOAK_CLIENT_ID=webapp
      - KEYCLOAK_CLIENT_SECRET=5106d698-2ea4-457b-a99e-8ba1952ae674
    links:
      - "nginx:keycloak.localtest.me"
      - "nginx:minio.localtest.me"

  minio:
    image: minio/minio
    container_name: minio.boringart
    restart: always
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: minio server /data

  mongo:
    image: mongo
    container_name: mongo.boringart
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express.boringart
    restart: always
    ports:
      - 8081:8081

  redis:
    image: redis
    container_name: redis.boringart
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog.boringart
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  keycloack:
    build: keycloak/dev
    container_name: keycloak.boringart
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
