FROM python:3.8.3-slim-buster

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt update && apt install file ffmpeg -y

RUN pip install --upgrade pip==20.1.1 && pip install pipenv==2020.6.2

WORKDIR /api
COPY Pipfile.lock /api/
RUN pipenv sync --dev

COPY . /webapp/
CMD ["pipenv", "run", "runserver_dev"]
